# Generated by Django 4.1.4 on 2022-12-08 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoMes',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
                ('receita_total', models.FloatField(blank=True, null=True)),
                ('despesa_fixa_total', models.FloatField(blank=True, null=True)),
                ('despesa_eventual_total', models.FloatField(blank=True, null=True)),
                ('saldo_final', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Orcamento do mes',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Receitas',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('codigo_despesa', models.CharField(choices=[('F', 'Despesa fixa'), ('E', 'Despesa eventual')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Despesas',
            },
        ),
    ]
