# Generated by Django 4.1.4 on 2022-12-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Usuario',
        ),
    ]
