# Generated by Django 4.1.4 on 2022-12-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resumomes',
            table='Resumo do Mes',
        ),
    ]
